### ISSUE TITLE
Issues when only 1 feature is inputted in crossValidate wrapper 

### ISSUE THREAD

**Issue by sourish279** [SydneyBioX/ClassifyR#72]
I've created an example using the iris data. The example shows that when the measurement assays only contain one feature within them, crossValidate wrapper returns an error. There is a different error when multiViewMethod = "merge" and when no multiview method is used.

## Setting up the data 

`irisFiltered = iris %>% 
 filter(Species %in% c("setosa", "versicolor"))`

`rownames(irisFiltered) = make.names(rownames(irisFiltered))`

`measurementsData = irisFiltered %>% 
  select(-Species) %>% 
  apply(FUN = function(x) x, ., MARGIN = 2, simplify = FALSE) %>% 
  lapply(data.frame)`

`outcome = irisFiltered$Species
names(outcome) = rownames(irisFiltered)`

## CrossValidate issue without merge multiview
`cvResults = ClassifyR::crossValidate(measurements = measurementsData,
                                             outcome = outcome,
                                             nFeatures = 1,
                                             selectionMethod = 't-test',
                                             classifier = "GLM",
                                             nRepeats = 1,
                                             nFolds = 3,
                                             nCores = 1)`

## CrossValidate issue with merge multiview
`cvResults = ClassifyR::crossValidate(measurements = measurementsData,
                                             outcome = outcome,
                                             nFeatures = 1,
                                             selectionMethod = 't-test',
                                             classifier = "GLM",
                                             nRepeats = 1,
                                             nFolds = 3,
                                             nCores = 1,
                                             multiViewMethod = "merge")`

**Comment by DarioS** [comment]
These two examples trigger a different error to the one intended. The data was filtered to the samples belonging to `"setosa"` and `"versicolor"` but the outcome factor still has three factor levels.

```r
> levels(outcome)
[1] "setosa"     "versicolor" "virginica" 
> table(outcome)
    setosa versicolor  virginica 
        50         50          0
```
The code which assigns samples to folds gets to virginica level and then fails because zero samples belong to it. I have now added a safety filter for this in prepareData: `outcome <- droplevels(outcome)`. This then allows us to deal with the real issue.  As expected, there was a missing `drop = FALSE` in selectMulti subsetting. It now all works for me. How about for you?

**Comment by sourish279** [comment]
Perfect works great now! Thanks, Dario (:
